package app.mapper;

import app.model.BulletinBoardData;
import app.model.BulletinBoardDataExample;
import app.model.BulletinBoardDataKey;
import java.util.List;

public interface BulletinBoardDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bulletin_board_data
     *
     * @mbggenerated Thu Dec 03 21:22:56 JST 2015
     */
    int deleteByPrimaryKey(BulletinBoardDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bulletin_board_data
     *
     * @mbggenerated Thu Dec 03 21:22:56 JST 2015
     */
    int insert(BulletinBoardData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bulletin_board_data
     *
     * @mbggenerated Thu Dec 03 21:22:56 JST 2015
     */
    int insertSelective(BulletinBoardData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bulletin_board_data
     *
     * @mbggenerated Thu Dec 03 21:22:56 JST 2015
     */
    List<BulletinBoardData> selectByExample(BulletinBoardDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bulletin_board_data
     *
     * @mbggenerated Thu Dec 03 21:22:56 JST 2015
     */
    BulletinBoardData selectByPrimaryKey(BulletinBoardDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bulletin_board_data
     *
     * @mbggenerated Thu Dec 03 21:22:56 JST 2015
     */
    int updateByPrimaryKeySelective(BulletinBoardData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bulletin_board_data
     *
     * @mbggenerated Thu Dec 03 21:22:56 JST 2015
     */
    int updateByPrimaryKey(BulletinBoardData record);
}