package app.mapper;

import app.model.UserRolesExample;
import app.model.UserRolesKey;
import java.util.List;

public interface UserRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_roles
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    int deleteByPrimaryKey(UserRolesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_roles
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    int insert(UserRolesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_roles
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    int insertSelective(UserRolesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_roles
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    List<UserRolesKey> selectByExample(UserRolesExample example);
}