package app.model;

public class BulletinBoardDataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bulletin_board_data.id
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bulletin_board_data.id
     *
     * @return the value of public.bulletin_board_data.id
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bulletin_board_data.id
     *
     * @param id the value for public.bulletin_board_data.id
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }
}