package app.model;

import java.util.Date;

public class BulletinBoardData extends BulletinBoardDataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bulletin_board_data.name
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bulletin_board_data.posting_date
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    private Date postingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bulletin_board_data.posting_content
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    private String postingContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bulletin_board_data.register_date
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    private Date registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bulletin_board_data.update_date
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bulletin_board_data.name
     *
     * @return the value of public.bulletin_board_data.name
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bulletin_board_data.name
     *
     * @param name the value for public.bulletin_board_data.name
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bulletin_board_data.posting_date
     *
     * @return the value of public.bulletin_board_data.posting_date
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public Date getPostingDate() {
        return postingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bulletin_board_data.posting_date
     *
     * @param postingDate the value for public.bulletin_board_data.posting_date
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public void setPostingDate(Date postingDate) {
        this.postingDate = postingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bulletin_board_data.posting_content
     *
     * @return the value of public.bulletin_board_data.posting_content
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public String getPostingContent() {
        return postingContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bulletin_board_data.posting_content
     *
     * @param postingContent the value for public.bulletin_board_data.posting_content
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public void setPostingContent(String postingContent) {
        this.postingContent = postingContent == null ? null : postingContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bulletin_board_data.register_date
     *
     * @return the value of public.bulletin_board_data.register_date
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bulletin_board_data.register_date
     *
     * @param registerDate the value for public.bulletin_board_data.register_date
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bulletin_board_data.update_date
     *
     * @return the value of public.bulletin_board_data.update_date
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bulletin_board_data.update_date
     *
     * @param updateDate the value for public.bulletin_board_data.update_date
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}