package app.model;

public class SchemaVersionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.schema_version.version
     *
     * @mbggenerated Thu Dec 03 21:22:56 JST 2015
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.schema_version.version
     *
     * @return the value of public.schema_version.version
     *
     * @mbggenerated Thu Dec 03 21:22:56 JST 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.schema_version.version
     *
     * @param version the value for public.schema_version.version
     *
     * @mbggenerated Thu Dec 03 21:22:56 JST 2015
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }
}