package app.model;

public class SystemPropertyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.system_property.key
     *
     * @mbggenerated Thu Dec 03 21:22:56 JST 2015
     */
    private String key;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.system_property.key
     *
     * @return the value of public.system_property.key
     *
     * @mbggenerated Thu Dec 03 21:22:56 JST 2015
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.system_property.key
     *
     * @param key the value for public.system_property.key
     *
     * @mbggenerated Thu Dec 03 21:22:56 JST 2015
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }
}