package app.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public UserInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameIsNull() {
            addCriterion("organization_name is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameIsNotNull() {
            addCriterion("organization_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameEqualTo(String value) {
            addCriterion("organization_name =", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameNotEqualTo(String value) {
            addCriterion("organization_name <>", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameGreaterThan(String value) {
            addCriterion("organization_name >", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameGreaterThanOrEqualTo(String value) {
            addCriterion("organization_name >=", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameLessThan(String value) {
            addCriterion("organization_name <", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameLessThanOrEqualTo(String value) {
            addCriterion("organization_name <=", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameLike(String value) {
            addCriterion("organization_name like", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameNotLike(String value) {
            addCriterion("organization_name not like", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameIn(List<String> values) {
            addCriterion("organization_name in", values, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameNotIn(List<String> values) {
            addCriterion("organization_name not in", values, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameBetween(String value1, String value2) {
            addCriterion("organization_name between", value1, value2, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameNotBetween(String value1, String value2) {
            addCriterion("organization_name not between", value1, value2, "organizationName");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("enabled is null");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("enabled is not null");
            return (Criteria) this;
        }

        public Criteria andEnabledEqualTo(Boolean value) {
            addCriterion("enabled =", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotEqualTo(Boolean value) {
            addCriterion("enabled <>", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThan(Boolean value) {
            addCriterion("enabled >", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("enabled >=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThan(Boolean value) {
            addCriterion("enabled <", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThanOrEqualTo(Boolean value) {
            addCriterion("enabled <=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledIn(List<Boolean> values) {
            addCriterion("enabled in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotIn(List<Boolean> values) {
            addCriterion("enabled not in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled not between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andActivateTokenIsNull() {
            addCriterion("activate_token is null");
            return (Criteria) this;
        }

        public Criteria andActivateTokenIsNotNull() {
            addCriterion("activate_token is not null");
            return (Criteria) this;
        }

        public Criteria andActivateTokenEqualTo(String value) {
            addCriterion("activate_token =", value, "activateToken");
            return (Criteria) this;
        }

        public Criteria andActivateTokenNotEqualTo(String value) {
            addCriterion("activate_token <>", value, "activateToken");
            return (Criteria) this;
        }

        public Criteria andActivateTokenGreaterThan(String value) {
            addCriterion("activate_token >", value, "activateToken");
            return (Criteria) this;
        }

        public Criteria andActivateTokenGreaterThanOrEqualTo(String value) {
            addCriterion("activate_token >=", value, "activateToken");
            return (Criteria) this;
        }

        public Criteria andActivateTokenLessThan(String value) {
            addCriterion("activate_token <", value, "activateToken");
            return (Criteria) this;
        }

        public Criteria andActivateTokenLessThanOrEqualTo(String value) {
            addCriterion("activate_token <=", value, "activateToken");
            return (Criteria) this;
        }

        public Criteria andActivateTokenLike(String value) {
            addCriterion("activate_token like", value, "activateToken");
            return (Criteria) this;
        }

        public Criteria andActivateTokenNotLike(String value) {
            addCriterion("activate_token not like", value, "activateToken");
            return (Criteria) this;
        }

        public Criteria andActivateTokenIn(List<String> values) {
            addCriterion("activate_token in", values, "activateToken");
            return (Criteria) this;
        }

        public Criteria andActivateTokenNotIn(List<String> values) {
            addCriterion("activate_token not in", values, "activateToken");
            return (Criteria) this;
        }

        public Criteria andActivateTokenBetween(String value1, String value2) {
            addCriterion("activate_token between", value1, value2, "activateToken");
            return (Criteria) this;
        }

        public Criteria andActivateTokenNotBetween(String value1, String value2) {
            addCriterion("activate_token not between", value1, value2, "activateToken");
            return (Criteria) this;
        }

        public Criteria andActivateLimitIsNull() {
            addCriterion("activate_limit is null");
            return (Criteria) this;
        }

        public Criteria andActivateLimitIsNotNull() {
            addCriterion("activate_limit is not null");
            return (Criteria) this;
        }

        public Criteria andActivateLimitEqualTo(Date value) {
            addCriterion("activate_limit =", value, "activateLimit");
            return (Criteria) this;
        }

        public Criteria andActivateLimitNotEqualTo(Date value) {
            addCriterion("activate_limit <>", value, "activateLimit");
            return (Criteria) this;
        }

        public Criteria andActivateLimitGreaterThan(Date value) {
            addCriterion("activate_limit >", value, "activateLimit");
            return (Criteria) this;
        }

        public Criteria andActivateLimitGreaterThanOrEqualTo(Date value) {
            addCriterion("activate_limit >=", value, "activateLimit");
            return (Criteria) this;
        }

        public Criteria andActivateLimitLessThan(Date value) {
            addCriterion("activate_limit <", value, "activateLimit");
            return (Criteria) this;
        }

        public Criteria andActivateLimitLessThanOrEqualTo(Date value) {
            addCriterion("activate_limit <=", value, "activateLimit");
            return (Criteria) this;
        }

        public Criteria andActivateLimitIn(List<Date> values) {
            addCriterion("activate_limit in", values, "activateLimit");
            return (Criteria) this;
        }

        public Criteria andActivateLimitNotIn(List<Date> values) {
            addCriterion("activate_limit not in", values, "activateLimit");
            return (Criteria) this;
        }

        public Criteria andActivateLimitBetween(Date value1, Date value2) {
            addCriterion("activate_limit between", value1, value2, "activateLimit");
            return (Criteria) this;
        }

        public Criteria andActivateLimitNotBetween(Date value1, Date value2) {
            addCriterion("activate_limit not between", value1, value2, "activateLimit");
            return (Criteria) this;
        }

        public Criteria andActivateFlagIsNull() {
            addCriterion("activate_flag is null");
            return (Criteria) this;
        }

        public Criteria andActivateFlagIsNotNull() {
            addCriterion("activate_flag is not null");
            return (Criteria) this;
        }

        public Criteria andActivateFlagEqualTo(Boolean value) {
            addCriterion("activate_flag =", value, "activateFlag");
            return (Criteria) this;
        }

        public Criteria andActivateFlagNotEqualTo(Boolean value) {
            addCriterion("activate_flag <>", value, "activateFlag");
            return (Criteria) this;
        }

        public Criteria andActivateFlagGreaterThan(Boolean value) {
            addCriterion("activate_flag >", value, "activateFlag");
            return (Criteria) this;
        }

        public Criteria andActivateFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("activate_flag >=", value, "activateFlag");
            return (Criteria) this;
        }

        public Criteria andActivateFlagLessThan(Boolean value) {
            addCriterion("activate_flag <", value, "activateFlag");
            return (Criteria) this;
        }

        public Criteria andActivateFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("activate_flag <=", value, "activateFlag");
            return (Criteria) this;
        }

        public Criteria andActivateFlagIn(List<Boolean> values) {
            addCriterion("activate_flag in", values, "activateFlag");
            return (Criteria) this;
        }

        public Criteria andActivateFlagNotIn(List<Boolean> values) {
            addCriterion("activate_flag not in", values, "activateFlag");
            return (Criteria) this;
        }

        public Criteria andActivateFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("activate_flag between", value1, value2, "activateFlag");
            return (Criteria) this;
        }

        public Criteria andActivateFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("activate_flag not between", value1, value2, "activateFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.user_info
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 01 18:07:57 JST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.user_info
     *
     * @mbggenerated Tue Dec 01 18:07:57 JST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}